### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wangzaistone** [WenRichard/QAmodel-for-Retrievalchatbot#1]
同学你好，你这个demo虽然感觉写的简洁清晰明了，对我有启发。能否请你把./data数据集也上传一下。
star，fork了，我也打算往问答方向走，看到你也在看《智能问答与深度学习》，希望能多交流

**Comment by WenRichard** [comment]
数据集的格式就是Q-Q+Q-A两种，具体的可以自己构造哦

**Comment by WenRichard** [comment]
> 同学你好，你这个demo虽然感觉写的简洁清晰明了，对我有启发。能否请你把./data数据集也上传一下。
> star，fork了，我也打算往问答方向走，看到你也在看《智能问答与深度学习》，希望能多交流

数据集的格式就是Q-Q+Q-A两种，具体的可以自己构造

**Comment by wangzaistone** [comment]
ok
